### ISSUE TITLE
output.festink: kill/death が 0 の時、値が送信されてこない

### ISSUE THREAD

**Issue by fetus-hina** [hasegaw/IkaLog#11]
Python よくわかりませんが、たぶん原因は https://github.com/hasegaw/IkaLog/blob/748beeb75487de19e452a19efab77b24388f11ca/ikalog/outputs/statink.py#L189 の `and` の後ろです。

送信ログのスクリーンショットとかあります: https://github.com/fetus-hina/stat.ink/issues/4

**Comment by hasegaw** [comment]
自分の kill を 0 にするパッチ
diff --git a/ikalog/outputs/statink.py b/ikalog/outputs/statink.py
index e1bd05a..da94c15 100644
--- a/ikalog/outputs/statink.py
+++ b/ikalog/outputs/statink.py
@@ -355,6 +355,7 @@ if __name__ == "__main__":

     # 各プレイヤーの状況を分析
     IkaScene_ResultDetail().analyze(context)
+    IkaUtils.getMyEntryFromContext(context)['kills'] = 0

     # stat.ink へのトリガ
     obj.onGameIndividualResult(context)

たしかに kill のフィールド自体が出力されていない
dhcp44-82:IkaLog hasegaw$ IKALOG_STATINK_APIKEY=X python3 ikalog/outputs/statink.py screenshots/ikabattle_20150815_1817.png
(snip)
{'agent': 'IkaLog',
 'agent_version': '0.01',
 'death': 3,
 'image_result': '(PNG Data)',
 'level': 28,
 'map': 'hakofugu',
 'my_point': 873,
 'rank_in_team': 3,
 'result': 'win',
 'rule': 'area'}
(snip)

修正テスト
diff --git a/ikalog/outputs/statink.py b/ikalog/outputs/statink.py
index e1bd05a..84c4a4b 100644
--- a/ikalog/outputs/statink.py
+++ b/ikalog/outputs/statink.py
@@ -186,7 +186,7 @@ class statink:
             f_type = field[0]
             f_statink = field[1]
             f_ikalog = field[2]
-            if (f_ikalog in me) and me[f_ikalog]:
+            if (f_ikalog in me) and (me[f_ikalog] is not None):
                 if f_type == 'int':
                     try:
                         payload[f_statink] = int(me[f_ikalog])
@@ -355,6 +355,7 @@ if __name__ == "__main__":

     # 各プレイヤーの状況を分析
     IkaScene_ResultDetail().analyze(context)
+    IkaUtils.getMyEntryFromContext(context)['kills'] = 0

     # stat.ink へのトリガ
     obj.onGameIndividualResult(context)
dhcp44-82:IkaLog hasegaw$

kill = 0 でも出るようになった
dhcp44-82:IkaLog hasegaw$ IKALOG_STATINK_APIKEY=X python3 ikalog/outputs/statink.py screenshots/ikabattle_20150815_1817.png
(snip)
{'agent': 'IkaLog',
 'agent_version': '0.01',
 'death': 3,
 'image_result': '(PNG Data)',
 'kill': 0,
 'level': 28,
 'map': 'hakofugu',
 'my_point': 873,
 'rank_in_team': 3,
 'result': 'win',
 'rule': 'area'}
 (snip)
 
 
最終的な修正
 
 dhcp44-82:IkaLog hasegaw$ git diff
diff --git a/ikalog/outputs/statink.py b/ikalog/outputs/statink.py
index e1bd05a..5758512 100644
--- a/ikalog/outputs/statink.py
+++ b/ikalog/outputs/statink.py
@@ -186,7 +186,7 @@ class statink:
             f_type = field[0]
             f_statink = field[1]
             f_ikalog = field[2]
-            if (f_ikalog in me) and me[f_ikalog]:
+            if (f_ikalog in me) and (me[f_ikalog] is not None):
                 if f_type == 'int':
                     try:
                         payload[f_statink] = int(me[f_ikalog])

本来の kill 値が出る
dhcp44-82:IkaLog hasegaw$ IKALOG_STATINK_APIKEY=X python3 ikalog/outputs/statink.py screenshots/ikabattle_20150815_1817.png
(snip)
{'agent': 'IkaLog',
 'agent_version': '0.01',
 'death': 3,
 'image_result': '(PNG Data)',
 'kill': 5,
 'level': 28,
 'map': 'hakofugu',
 'my_point': 873,
 'rank_in_team': 3,
 'result': 'win',
 'rule': 'area'}
(snip)

**Comment by hasegaw** [comment]
Fixed in commit 47ba39cbd46fa1022618b78749f8e8e7219b1de5. Thanks!

**Comment by hasegaw** [comment]
HotFix (stat.ink対応暫定版実行ファイル、起動までのみテスト)
https://dl.dropboxusercontent.com/u/14421778/IkaLog/WinIkaLog20150928a_statink.zip
