### ISSUE TITLE
outputs/videorecorder: Fails to pass the argument(s)

### ISSUE THREAD

**Issue by hasegaw** [hasegaw/IkaLog#132]
A user reported:
試合開始時およびリザルト表示後に、自動録画スクリプトが以下の様なエラーを出力して動作しません。 >> Line 126　(File "E:~~~~~\ControlOBS.au3"); $stop = StringCompare($CmdLine[1], 'stop') == 0 $stop = StringCompare(^ ERROR Error: Array variable has incorrect numbers of subscripts or subscript dimension range exceeded. << ControlOBS.au3 の126行目、$CmdLine[1]を$CmdLine[0]とすると、上記エラーは発生せず、録画は開始されますが終了はされませんでした。 「ひたすらレギュラーマッチ」様の改造スクリプトに置き換えて動作を確認すると、エラーは起きず動画も録画開始はしませんが、自動処理のタイミングでスクリプトに引数を与えなかった場合の動作をしました。（リファレンスが表示されました） 以上のことから、IkaLogからControlOBS.au3を呼び出す際に、「start」「stop」といった引数がau3スクリプトに渡されていように見られます。 よろしくご確認ください。

Insights:
1. The user indicates IkaLog doesn't provide arguments to the script (and the isolation seems true as far as sodoko-san's version showed usage window.)
2. https://github.com/hasegaw/IkaLog/blob/master/ikalog/outputs/videorecorder.py#L143 should always provide "stop" or "start" as 1st argument.
3. https://github.com/hasegaw/IkaLog/blob/master/ikalog/outputs/videorecorder.py#L146 uses os.system().

Actions:
1. Test if the code works in a directory with non-ASCII characters
2. Test if the cods works in a directory with space character (0x20)
3. os.system() should be altered with another method, like as https://github.com/hasegaw/IkaLog/blob/master/ikalog/version.py#L27

**Comment by leo-murahashi** [comment]
レポートを受理していただきありがとうございます。
私の環境でのau3スクリプトの設置場所は、以下のとおりです。
E:\WinIkaLog20160128_220730_da38180\tools
レポート時に省略してしまい、申し訳ありませんでした。

Thank you for pick up my report, and I'm sorry for omitting the au3 script file path.
File path in my environment is as follows.
E:\WinIkaLog20160128_220730_da38180\tools

**Comment by sodoko-ika** [comment]
お役にたてなかったようで残念です。
インストールフォルダに合わせた設定で正しくWinIkaLogを設定されておられるかは情報が無いのでなんとも言えないのですが、E:ドライブに設置されてるようなので、その辺りが怪しい気はしています。

素人判断で思いついたのですが、現在のIkaLogで出力している IkaConfig.yaml があれば、各種設定画面に指定している設定値が正しいかとかは分かるかなと思いました。

**Comment by leo-murahashi** [comment]
sodoko様よりご提案いただいた、私の環境の詳細情報とWinIkaLogの設定、エラー時のメッセージ等のスクリーンショットを送ります。また同じくご提案いただいた通り、ファイルの設置場所を、**E:\IkaLog** に変更しました。
　WinIkaLog添付のControlAmarecTV.au3の直接実行結果およびWinIkaLogから呼び出された際のエラーは、OBSの場合とほぼ同じで、エラー発生時の行番号が異なるだけでした。
　その他必要な情報がございましたら、ご指定ください。よろしくお願いいたします。

■OSのバージョン
エディション	Windows 10 Pro
バージョン	1511
OS ビルド	10586.122

■WinIkaLogファイルの設置場所
E:\IkaLog

■au3スクリプトの設置場所と各ファイル名およびその内容
設置場所　E:\IkaLog\tools
WinIkaLog添付　ControlAmarecTV.au3
http://sodoko-ika.blogspot.jp/2015/10/controlamarectvau3.html
　　　　　　　　ControlAmarecTVplus.au3
http://sodoko-ika.blogspot.jp/2016/03/controlamarectvau3amarectv.html
　　　　　　　　ControlAmarecTVplus2.au3
http://sodoko-ika.blogspot.jp/2016/03/amarectv-display-amarectv.html
　　　　　　　　ControlAmarecTVplus3.au3
WinIkaLog添付　ControlOBS.au3

■設定内容やエラー表示の際のスクリーンショットは、以下で公開しました。
https://drive.google.com/folderview?id=0B0_MtIUOBBWYV1FaR2dGNUs5Qzg&usp=sharing
・各ファイル名と内容は以下の通りです。
Windows_ver.png　　WindowsOSのバージョン情報
WinIkaLog_autoRec_setting_OBS.png　　→OBS使用時のWinIkaLogの自動録画設定内容
ControlOBS_direct.png　　→ControlOBS.au3 ファイルをダブルクリックで実行した際のエラー
autoRec_error_OBS.png　　→WinIkaLogで自動録画を開始しようとした際のエラー
WinIkaLog_autoRec_setting_AmarecTVplus2.png　　→AmarecTVplus2スクリプト使用時のWinIkaLogの自動録画設定内容
autoRec_error_AmarecTVplus2_1.png　　→WinIkaLogで自動録画を開始しようとした際の結果1
autoRec_error_AmarecTVplus2_2.png　　→WinIkaLogで自動録画を開始しようとした際の結果2
autoRec_error_AmarecTVplus2_3.png　　→WinIkaLogで自動録画を開始しようとした際の結果3

■IkaConfig.yami の内容は、以下の通りです。（APIキー等は伏せました）
>
boyomi: {Enable: false, host: 127.0.0.1, port: '50001'}
csv: {CsvFilename: 'E:\IkaVideo\IkaData\ika.csv', Enable: true}
cvcapture: {Deinterlace: false, File: '', Source: amarec, SourceDevice: LGP Stream
    Engine}
json: {Enable: true, JsonFilename: 'E:\IkaVideo\IkaData\ika.json'}
obs: {AutoRenameEnable: true, ControlOBS: 'E:\IkaLog\tools\ControlAmarecTVplus2.au3',
  Dir: 'E:\IkaVideo\', Enable: true}
screenshot: {Dir: "C:\\Users\\user\\Google \u30C9\u30E9\u30A4\u30D6\\IkaShot", MiiveseDrawingEnable: false,
  ResultDetailEnable: true}
slack: {Enable: false, botName: IkaLog, url: ''}
stat.ink: {APIKEY: XXXXXXXXXX, Enable: true, ShowResponse: true,
  TrackObjective: true, TrackSplatzone: true}
twitter: {AccessToken: XXXXXXXXXX, AccessTokenSecret: XXXXXXXXXX,
  AttachImage: true, ConsumerKey: '', ConsumerKeyType: ikalog, ConsumerSecret: '',
  Enable: true, Footer: '', TweetKd: true, TweetMyScore: true, TweetUdemae: true,
  UseReply: false}
websocket_server: {Enable: false, port: 9090}
<

**Comment by sodoko-ika** [comment]
あれから気になっていたので、掲載していただいた IkaConfig.yami をコピペして試してみたのですが、変に改行コードが入るか何かで、バージョンを合わせたWinIkaLogでも読めなかったです。
実行する制御スクリプトに　E:\IkaLog\tools\ControlOBS.au3　（多分初期値）が入ってきます。

今お使いのyamlファイルをどこか別のところへ避けていただいて、WinIkaLogを起動->stat.inkさんとtwitterのapiキーをWinIkaLog上で消した後で->applyして、yamlファイルのまま（若しくはzipにするとか）どこかへ上げて頂いた方が良いかもしれません。

もしくは、本当にyamlファイルが壊れている可能性も僅かにあるかもなので、yamlファイルを別のフォルダへ移動させた状態で WinIkaLog を起動して自動録画とjson,csvの辺りを設定->applyで新規に保存したWinIkaLogで試してみるのも（面倒かもしれませんが…）アリかもしれません。

あと、自動録画用のスクリプトですが、↓にあるのが一番簡潔になっているバージョンです。（わたしも普段使いしています）宜しければお使いください。
https://github.com/hasegaw/IkaLog/blob/dev/tools/ControlAmarecTV.au3

**Comment by leo-murahashi** [comment]
安定版 WinIkaLog20160119_232120_33bf400 にてCドライブ上に環境を再構築してみました。
同時に、sodoko様よりお知らせいただいた新しいControlAmarecTV.au3 に差し替えてテストしてみましたが、やはり引数なしでau3スクリプトを起動した際のusageが表示されました。

yamiファイルを圧縮したものをIkaConfig.zip として、下記にて公開しましたのでご確認ください。
https://drive.google.com/folderview?id=0B0_MtIUOBBWYV1FaR2dGNUs5Qzg&usp=sharing

明後日のアップデートもありますので、本件については一旦探索を中断します。
またお手すきの際にご確認いただければと思います。
よろしくお願いいたします。

**Comment by sodoko-ika** [comment]
![videofiles](https://cloud.githubusercontent.com/assets/17638973/13571449/6993fd76-e4b8-11e5-850a-b8b8e4c4fe3f.png)

WinIkaLog20160119_232120_33bf400  + いつも使っているControlAmarecTV.au3 + 頂いたyamlファイルそのまま + 書かれていたIkaVideo～のフォルダを追加した環境で試しましたが、手元の環境では、問題なく録画出来ました。
※ファイルのリネームに1回失敗してますが、普段使わない機能なので適当に設定していたタイミングが早すぎたようです。

こちらで問題なく動作しましたので、お使いの環境だけで起こる現象の可能性が高そうです。

元気が無いので試せませんが、ひょっとしてWinIkaLog_ja.bat 経由で起動しないと起こる現象でしょうか？
この辺りはよく分かりません。
残念ながら、わたしの知識では、これ以上はお手上げです。

**Comment by hasegaw** [comment]
Usage まで出ているのであれば呼び出し自体はできているはずです。引数が渡らないのが謎ですね。
そのうちに子プロセスをたたくコードを変えてみます。

**Comment by tsukaby** [comment]
Windows 10 Home
WinIkaLog20160610_105425_b1915d2
で私も同様の問題が再現しました。ControlAmarecTV.au3だと引数が渡ってないような挙動。ControlOBS.au3だとエラーが出る、という状況です。

![2016-08-19 21 20 16](https://cloud.githubusercontent.com/assets/6133458/17809891/9c4ecc8c-6654-11e6-9c87-1dcbb3337252.png)

**Comment by hasegaw** [comment]
![2016-08-20_02 52 33](https://cloud.githubusercontent.com/assets/2528004/17819273/23bc3218-6682-11e6-9e59-b32f34694b6c.png)

518bc61 適用前のバージョンで、こんなかんじで autoit.exe のパスを指定すれば動くらしい

**Comment by tsukaby** [comment]
追加報告

```
Windows 10 Home
WinIkaLog20160610_105425_b1915d2
```

この環境下で上記のスクショのパス指定で上手く行きましたので、どうやら引数が渡ってないのではなく、引数は渡っているが起動方法が良くないようでした。ファイルの関連付け?あたりが関係しそうな感じでした。

subprocess.callでは解決せず。またそちらの方式だと上記スクショのパス指定は動きませんでした。

ControlAmarecTV.au3は正しく動きましたが、ControlOBS.au3はエラーは出なくなりましたが、OBS自体が起動せず。

**Comment by hasegaw** [comment]
OBS自体が起動しないとはどういうことです？

**Comment by tsukaby** [comment]
ControlOBS.au3を指定した場合、録画タイミングが来るとOBSが起動して録画が始まって・・・となると思いますが、そのタイミングでOBSが起動しませんでした。
IkaLog console上ではちゃんと録画の `Running ... start` は出ているのですが。

**Comment by hasegaw** [comment]
このスクリプト自体は OBS を起動する処理はしません。録画開始ボタンを見つけて押すだけです。

**Comment by tsukaby** [comment]
あ、なるほど・・・　予めOBSを起動して録画用の設定をしておく必要があったのですね。ありがとうございます。試してみます

**Comment by tsukaby** [comment]
OBSの録画も動きました。ありがとうございました

**Comment by hasegaw** [comment]
workaround もわかっていて IkaLog 自体の問題ではないようなので close
