### ISSUE TITLE
stat.inkへpostするところでjson.decoder.JSONDecodeErrorが出力されてpostできない

### ISSUE THREAD

**Issue by kubosho** [hasegaw/IkaLog#147]
- OS: OS X El Capitan 10.11.2
- キャプチャーカード: Blackmagic Design Intensity Shuttle for USB 3.0
- python3 version: Python 3.5.1

エラーログは以下の通りです。
https://gist.github.com/kubosho/c8f754b94785e01e4aaf#file-ikalog_statink_post_error-txt

役にたつかどうかは分からないですが1試合分のログも置いておきます。
https://gist.github.com/kubosho/c8f754b94785e01e4aaf#file-battle-log

---

## 試したこと

- IkaLogを最新版にした
    - https://github.com/hasegaw/IkaLog/tree/0d372d4ed82cf75d9119ea6e2d5fd705aae3e56d のバージョンを使っていたので https://github.com/hasegaw/IkaLog/tree/6d4629cbe4bb3d849bd39b9cac74100d04cf9aa4 に更新しました。
- `IkaConfig.py` を更新

`IkaConfig.py` が古い形式のままだったので、以下のようなエラーが出ていました。

```
Traceback (most recent call last):
  File "IkaLog.py", line 49, in <module>
    capture, OutputPlugins = IkaConfig().config(args)
TypeError: config() takes 1 positional argument but 2 were given
```

そのため、`IkaConfig.py.sample` を元に以下のように設定を書き直しました。
（可読性を高めるためコメントアウトしている部分は削除しました）

https://gist.github.com/kubosho/c8f754b94785e01e4aaf#file-ikaconfig-py

**Comment by hasegaw** [comment]
fetus-hina/stat.ink#113 が影響しているかもしれない？

**Comment by kubosho** [comment]
@hasegaw 
試しに9:10頃に1戦してみたところ正常にstat.inkへデータをpostすることができました。
またIkaLogによる解析が正常におこなわれていたこと、またその後のstat.inkへのpostが上手くいかなかったことを考えて、stat.ink側の更新により影響が出ていたと考えられます。

stat.ink側の更新によりpostできなかった可能性を考慮できてなかったです。申し訳ないです。
また、関係しているかもしれない更新を書いていただきありがとうございます。
