### ISSUE TITLE
プロダクトロゴの策定

### ISSUE THREAD

**Issue by southws** [hasegaw/IkaLog#289]
きっかけ:
[https://twitter.com/rioriost/status/736891481957371904]
---
## Ikalogステッカーが欲しいな。誰かデザインしようよ。
- ノートPCの背面に貼れるような何か
- パワポ等の発表の時に看板になるような何か
- スプラッシュ画面で表示できる何か
- 要件
  - 見たら一発でイカのアレと何か関係あるらしい、と分かる
  - （ロゴ用途に限っては）.eps なり .ai なりのパスでデザインする

**Comment by southws** [comment]
叩き台（拙作）:
1. [https://www.dropbox.com/s/qohvbkm3qky1dux/IkaLog_Logo_draft.png]
2. [https://www.dropbox.com/s/mcq6d7k2a1rdooi/IkaLog_Logo_draft2.png]

− ヒラギノ丸ゴW4 のロゴ使用は権利的にクリアなので、その点は安心
   − [http://www.screen.co.jp/ga_product/sento/support/licensefaq.html]
− 今は１〜２色に抑えているが、スプラトゥーンはカラフルなのがウリなので３色以上に増やしていいかも
   − モノクロになった時のことを考えながら配置する必要あり

**Comment by southws** [comment]
上記観点からちょっと手直ししました。

− 基本形
![](https://photos-2.dropbox.com/t/2/AABC5CTdhZKHo9ATy28LrrSNnztScIWNksXpwb1yHGCqPw/12/32912581/png/32x32/1/_/1/2/IkaLog_Logo_draft3.png/EPGE-RgYptoKIAEgAigBKAc/6IwSEh1tEANdu7ZpH_Qv2_nqC6ZcoCFrIMkYuXgR1QM?size=320x240)
− 基本形（グレースケール）
![]()
− スクウェア
![](https://photos-3.dropbox.com/t/2/AAD7u5pMR0yLI6cKcnTLGadfPbNrXl9GhgYqosGSyFHBVg/12/32912581/png/32x32/1/_/1/2/IkaLog_Logo_draft3_sq.png/EPGE-RgYptoKIAEgAigBKAc/JNCX793FUg5-dkbFU3SW927734szjeu93CTbjW1WEuY?size=1600x1200&size_mode=3)
− スクウェア（グレースケール）
![]()

**Comment by hasegaw** [comment]
ご提案ありがとうございます。 issue きっかけで他の案も出てきました。
![o6xweda2](https://cloud.githubusercontent.com/assets/2528004/15757611/6f2d084a-2941-11e6-885f-fe5d569707f5.png)

ただ、ロゴやスプラッシュ画面を一種類にこだわる理由はないと思っています。

**Comment by southws** [comment]
基本的に賛成です。
ロゴに限って言えば縮小・拡大耐性や二値化して潰れないか、といった考慮すべき観点がありますが、ステッカー作る上では同じデザインをたくさん並べるより、種類があったほうが楽しくていいと思います。

『パスで』というのはラスターデザイン派の方を萎縮させてしまいそうで少々不用意でした。これが必須要件となるのはロゴ用途に限る(ステッカー類向けの絵だったら問題ないのではないか)という見解です。

**Comment by hasegaw** [comment]
![Uploading Screen Shot 2016-07-03 at 7.52.40 PM.png…]()
wktk

**Comment by hasegaw** [comment]
![screen shot 2016-07-03 at 7 52 40 pm](https://cloud.githubusercontent.com/assets/2528004/16545035/dd3d45a6-4157-11e6-9964-af7a5adec762.png)
wktk

**Comment by hasegaw** [comment]
（や、やりすぎなのでは！？）

**Comment by hasegaw** [comment]
他にもロゴができた
![ikalog_logo1](https://cloud.githubusercontent.com/assets/2528004/17077116/6d613dca-50ff-11e6-9357-9ba894459444.png)

**Comment by hasegaw** [comment]
ステッカーのオーダー忘れてる

**Comment by hasegaw** [comment]
ステッカーをオーダーしたぞ。
![screen shot 2016-10-24 at 18 10 42](https://cloud.githubusercontent.com/assets/2528004/19639898/4d949ae6-9a15-11e6-8aea-653163568f67.png)

**Comment by hasegaw** [comment]
解像度的に厳しいといわれてしまったのでとりあえずベクトルデータベースの丸タイプのみ発注
（意図した形でできてこないかもしれない）

**Comment by hasegaw** [comment]
![screen shot 2016-10-28 at 1 07 14](https://cloud.githubusercontent.com/assets/2528004/19775301/f2f05fce-9caa-11e6-96fd-237db715ca0e.png)

**Comment by hasegaw** [comment]
![ikalog_sticker](https://cloud.githubusercontent.com/assets/2528004/19916868/6f1be708-a101-11e6-94fc-9b0e5cf2b99f.jpg)

@southws よろしければサンプルお送りしますのでTwitterなどで送付先お知らせください。
