### ISSUE TITLE
Pythonicなコードへのリファクタリング

### ISSUE THREAD

**Issue by mzsm** [hasegaw/IkaLog#3]
* コーディングルールのPEP8準拠(関数名、変数名の大文字小文字、キャメルケースorスネークケース等)
* ディレクトリ構成(パッケージ)の整理
等…

**Comment by mzsm** [comment]
大文字or小文字、スネークケースorキャメルケースの修正に関しては機械的に判断できるのですが、パッケージの整理についてはどういう方針でやるか決めないといけないですね

**Comment by hasegaw** [comment]
input.cvcapture -> input/cvcapture
input.vlcstream -> input/vlcstream

としたいけども

import input.cvcatpure
cvcapture.cvpcapture()

とするのは微妙ですし、かといって input/__init__.py で

from input.cvcapture import cvcapture

とすると不要なクラスまで毎回ロードしちゃうのがなんともいえないですね。
何かおすすめはありますか？

**Comment by hasegaw** [comment]
input/
  cvcapture.py
  vlcstream.py
output/
  console.py
  twitter.py
scene/
  gamestart.py (game_start.py のほうがいいかな?)
  lobby.py 

シーンについては、中で使うマッチングを別に切り出したい。
たとえばシーンでわけるとゲーム進行中にマッチングする画像が多数あるので上記方針だと、
ゲーム進行中の画面解析をする部分のファイルが大きくなるので下記のイメージで分解できると理想かな。

scene.ingame
scene.ingame.kill_detector
scene.ingame.deatch_detector

**Comment by mzsm** [comment]
````python
# input/cvcapture.py
class CVCapture(object):
    pass


# input/vlcstream.py
class VLCStream(object):
    pass


# input/__init__.py
from .cvcapture import CVCapture
from .vlcstream import VLCStream


# main.py
from input import *

CVCapture()
````
みたいな感じで、\_\_init\_\_.pyでそのパッケージで使う主なクラスやメソッドを読み込むのはよく見ますね。

**Comment by hasegaw** [comment]
なるほど、それが現実解かなぁ。
# 最終的には、この上で、プラグイン方式っぽくならないように import で自動的にクラスをインポートするような実装にしたいかな。

**Comment by mzsm** [comment]
````python
# input/foo.py
class Foo(object):
    pass
````
を追加した場合に、\_\_init\_\_.pyに追記することなく
````python
# main.py
from .input import *

Foo()
````
と出来るようにしたいということでしょうか。
そうだとすると、listdirやgrobでパッケージ内のモジュール一覧を取得して、ひとつずつimportしていくような仕組みが必要になりますね
例: https://github.com/Dan-in-CA/SIP/blob/master/plugins/__init__.py

**Comment by hasegaw** [comment]
はい、そうです。例のがまさに想定してたイメージですね。（きっとできるだろうと思いました）

**Comment by mzsm** [comment]
* IkaLog.py
* IkaUI.py
    * メインとなるモジュールなのでそのまま
* IkaConfig.py.sample
    * config.py.sampleにリネーム
* IkaUtils.py
    * utils/\_\_init\_\_.pyにリネーム
* IkaOutput_*.py
    * output/*.pyにリネーム
* IkaPanel_*.py
    * panel/*.pyにリネーム
* IkaScene_*.py
    * scene/*.pyにリネーム
* IkaAnonymizer.py
* IkaEngine.py
* IkaGlyphRecoginizer.py
    * Ikaだけ消してそのまま？

こんな感じでしょうか。

**Comment by hasegaw** [comment]
IkaAnonymizer.py
-> こちらで tools/ に移動します。

IkaGlyphRecoginizer.py
-> utils.GlyphRecoginizer などに将来的には移してもいいかも。
現時点では Ika 消して移しても、保留でもいいです。

**Comment by hasegaw** [comment]
IkaPanel_*.py は IkaUI.py からしか使われないので ui/panel/ でもいいかもしれない。

**Comment by mzsm** [comment]
ソースと、それ以外のファイルが混在しているので、

    IkaLog/
    ├doc/
    ├test/
    ├tools/
    ├src/
    │├input/
    │├output/
    │├scene/
    │├utils/
    │└engine.py
    ├lib/
    │└videoinput.dll
    ├IkaLog.py
    ├IkaUI.py
    ├config.py.sample
    ├README.md
    └INSTALL

みたいにsrcディレクトリを1つ掘って、分離させてもいいかもしれないですね

**Comment by hasegaw** [comment]
ソースディレクトリを作ってもいいですね。
第三者による IkaLog 内蔵ツール作成まで風呂敷を広げて想定すると、 lib 的にしておいて、メインモジュールを実行すると lib の中にある IkaUI.py/IkaLog.py が実行されたりする感じがいいかもしれないと思うんですが、どうでしょう。（ というところから当初 lib/ を掘るか悩んでいた）

lib か、トップモジュール名として ikalog かな。。。

**Comment by hasegaw** [comment]
ikalog トップモジュールとする場合 input/output が Python の予約語とかぶらないのも利点。

IkaUI.py -> UI版bootstrap
IkaLog.py -> CLI版bootstrap (もしくは現在のIkaLog.py)
ikalog/現在のIkaUI.py
ikalog/現在のIkaLog.py
ikalog/engine.py
ikalog/input/
ikalog/output/
ikalog/scene/

videoinput.dll をどこにおくかはなやみますね。
ext/videoinput.dll
lib/videoinput.dll
ikalog/ext/videoinput.dll
ikalog/lib/videoinput.dll

あたりとか... でどうでしょう？おかしいですかね？普通に src のほうがよい？

**Comment by mzsm** [comment]
ikalogにするほうがいいですかねー。
input/outputは複数形にしても良いかも。

**Comment by hasegaw** [comment]
inputs/outputs にするかは、他に複数形のモジュール名が使われていたら考えたいです。何か思いつくものあります？

複数形にするなら scene -> scenes だけども

ikalog.scene.lobby
ikalog.scenes.lobby

なら前者のほうがインポートする側からは自然かな？と思うので。 input/output が単数形なのも同じ理由です。

ikalog.input.VLCStream
ikalog.inputs.VLCStream

**Comment by mzsm** [comment]
dllはlib/videoinput.dllが良いんじゃないでしょうか

**Comment by hasegaw** [comment]
では dll は lib/ にしましょう。

**Comment by hasegaw** [comment]
http://docs.python.jp/2.6/library/codecs.html
Python の標準モジュールが複数形使っていますね。なら複数形にしてもいいかなあ。

**Comment by mzsm** [comment]
複数のinput元をまとめているパッケージなので、複数形のinputsでいいと思います。

**Comment by hasegaw** [comment]
了解です。

**Comment by mzsm** [comment]
:+1:

**Comment by mzsm** [comment]
モジュール整理の作業はこちらで行うほうがよいですか？

**Comment by hasegaw** [comment]
量があって大変のである程度分担しましょう。でも私が最初にやるよりは mzsm さんに input, scene, output をとりあえずひとつずつでも整理してもらうのがありですかね。方向性が判れば私も手伝えるので。

**Comment by mzsm** [comment]
ではある程度までやってみます

**Comment by mzsm** [comment]
残件：
* IkaPanel_*.pyの移動
* クラス名・メソッド名の変更

クラス名・メソッド名の変更はこちらで行いたいと思います

**Comment by hasegaw** [comment]
了解です。
作業するときは Conflict を避けるために twitter or slack にてコメントください。

**Comment by hasegaw** [comment]
その後進展しないので close
