### ISSUE TITLE
プラグインシステム

### ISSUE THREAD

**Issue by mzsm** [hasegaw/IkaLog#36]
exe化したとき、pluginsフォルダの下にpythonスクリプト置くと任意で機能を追加できるような仕組みがあると良いのでは

**Comment by hasegaw** [comment]
考えてはいますが、理由があり、やっていません。今後の課題とさせてください。

お気づきかもしれませんが、exe化したバージョンは GitHub にあるバージョンに対して
ユーザの利便性を向上させるため、あるパッチを入れたものをビルドしています。

EXE版に動的に Python コードを追加させると、そのコードからまわりのクラスの状態
などがたどれてしまいますし、そういう隠しておきたいデータを読めてしまいます。
Python の仕組み的にプライベートメソッド／フィールドの仕組みもありません。

**Comment by hasegaw** [comment]
現時点の方針では実装しない。

・私がリリースしている EXE バイナリに対して外部の Python モジュールはロードさせない。
・追加モジュールがあれば Pull Request などは歓迎。このレポジトリに入れば EXE ファイル内に組み込まれる。
・GitHub にある IkaLog コードに対して自分でモジュールを書き足して動かすことは自由。
・第三者が配布する EXE バイナリを入手した場合はどのようなコードが入っているか、私は関与しない。
