### ISSUE TITLE
utilsディレクトリの名称変更

### ISSUE THREAD

**Issue by mzsm** [hasegaw/IkaLog#4]
現在、ルートにIka*というファイル名のスクリプトが散らばっていますが、これらはoutput, panel, scene等のパッケージまたはモジュールに整理していくべきだと思います。

しかし現状、「ユーティリティ」という名の付くものが、utilsディレクトリとIkaUtilsの2つ存在しています。
Pythonではディレクトリ名がそのままパッケージ名、ファイル名がそのままモジュール名になりますので、IkaUtils.pyをutilsというパッケージまたはモジュールにしようとすると、既存のutilsと名前が競合してしまいます。
現状、utilsディレクトリにあるものは役割的にはscriptsかtoolのほうが適切なように思えますので、どちらかに変更すべきではないでしょうか。

**Comment by hasegaw** [comment]
了解です。 tools/  しましょうか。 Python ベースのおまけツールや AutoIT ベースのツールもはいっていますので。
