### ISSUE TITLE
outputs/statink: L3リールガンDがおそらく送信されない

### ISSUE THREAD

**Issue by fetus-hina** [hasegaw/IkaLog#40]
実際には試してないですがソースを眺めていたら動きそうにないです
https://github.com/hasegaw/IkaLog/blob/9ba77582c1aef91782e2e6b312104d63e3d17691/ikalog/outputs/statink.py#L162

**Comment by hasegaw** [comment]
キャッチいただきありがとうございます。
とりあえず 4cd94e115d5b79269344120b4f3d22a18d443ad4 で直しておきましたがほかのブキもちゃんと確認していないので、今後ちゃんと整理してユニットテスト書かないといけませんね。

**Comment by hasegaw** [comment]
ユニットテストなどは別 issue などとして対応するため本件はこれにてクローズ
