### ISSUE TITLE
deadly_weapons.ja.model: Needs update

### ISSUE THREAD

**Issue by hasegaw** [hasegaw/IkaLog#410]
@hasegaw サンプルファイル収集しました https://t.co/8ChKrNHHvM に置いてあります。スクスロ&gt;スネオ、ボールド&gt;ボルネオ、ホッカス&gt;ホッブラもうまく認識できてないようなので、サンプルに含めています。

**Comment by wkoichi** [comment]
モデル更新後に、ボールド、ホッカス、ダイナモバーンド、L3Dでキルされると、それぞれのブキでキルされたと正しく認識されました。スクスロは野良で出会わないので、まだ未確認です。

見落としていたのですが、N-ZAP85にキルされると、N-ZAP83にキルされたと認識されたので、サンプルファイルを https://dl.dropboxusercontent.com/u/459722/N-ZAP85.zip に置いておきます。

**Comment by hasegaw** [comment]
見てみます。
