### ISSUE TITLE
IkaUI: Options 画面の Apply などのボタンが表示されない場合がある

### ISSUE THREAD

**Issue by hasegaw** [hasegaw/IkaLog#47]
環境によっては Options 画面の Apply などのボタンが表示されない場合がある。
悪い環境ではウインドウサイズを変更しても見えない。ボタンが並んでいるパネルも縦幅設定を見直す。

**Comment by hasegaw** [comment]
Windows 7 でのみ再現するらしい。

**Comment by gleentea** [comment]
twitterタブの設定項目が多すぎて初期サイズではボタン見えませんが、#98 でリサイズすればちゃんと見えるようになる修正を行ったのでクローズで良いのではないでしょうか

**Comment by hasegaw** [comment]
:+1:
