### ISSUE TITLE
プラグインの設定項目とUIの切り離し

### ISSUE THREAD

**Issue by ExceptionError** [hasegaw/IkaLog#50]
# 経緯

IkaUIのon_config_XXX系呼び出しを各種プラグインが実装しているが、その内部でGUI前提の振る舞い(refresh_ui）を持っていおり、IkaUI以外のアプリを作ろうとしたときに利用できない。

これを改善できるとIkaLogとIkaUI以外のアプリが作りやすくなる(というか作ろうとしたときにこの問題に引っかかった)。
別アプリは別のメソッド呼び出しで設定を読み書きするという実装にするとプラグインのアプリ用途の実装が肥大化してプラグインの本質の処理が埋まっていってしまうのでそれは避けたい。　
# アイデア
## config周り
- [ ] context['config']を受け取ってその内容を参照し、自身の振る舞いを更新するメソッドを用意する。
- [ ] context['config']を受け取ってその内容を更新し、自身の振る舞いをエンジンに返すメソッドを用意する。
- [ ] IkaUIが持っているconfigの読み書きを汎用化し、Ikaアプリで共通の設定を利用できるようにする。
## UI周り
- [ ] プラグイン内に存在するGUI構築処理をikalog.ui以下に移行する。

**Comment by ExceptionError** [comment]
方針が特に問題なさそうだったら少しづつ作業してプルリク出していきます！

**Comment by hasegaw** [comment]
問題ないです。がboyomi はとりあえず今までの方法で実装してしまいました。がんがんいじっちゃってください。

**Comment by hasegaw** [comment]
ビデオキャプチャの設定部分のみ ikalog/ui/ 以下に移動済み。 (devブランチ)

**Comment by hasegaw** [comment]
新プラグインインターフェイスで実施
