### ISSUE TITLE
AmarecTVを経由しないキャプチャが出来ない

### ISSUE THREAD

**Issue by gleentea** [hasegaw/IkaLog#60]
AmarecTVを経由せずHWから直キャプ（Realtime Capture from HDMI grabber+HW指定）するとエラーになる。
使用HWはMonsterX U3.0Rです、ikalogは2015/10/31時点の最新（WinIkaLog20151029_091612_d528a86.zip）です。
AmarecTV経由（Capture through AmarecTV）なら問題ないので優先度は低いかと思います。

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\IkaLog\Python34\lib\threading.py", line 920, in _bootstrap_inner
  File "C:\IkaLog\Python34\lib\threading.py", line 868, in run
  File "IkaUI.py", line 191, in engine_thread_func
  File "z:\hasegaw\work\IkaLogPY2EXE\ikalog\engine.py", line 287, in run
  File "z:\hasegaw\work\IkaLogPY2EXE\ikalog\engine.py", line 212, in process_frame
  File "z:\hasegaw\work\IkaLogPY2EXE\ikalog\scenes\result_detail.py", line 319, in match
  File "z:\hasegaw\work\IkaLogPY2EXE\ikalog\utils\ikautils.py", line 128, in matchWithMask
ValueError: operands could not be broadcast together with shapes (1080,1920) (720,1280)
```

**Comment by hasegaw** [comment]
手元の MonsterX U3.0R ではまったくフレームがとれていません。
python3 ikalog/inputs/cvcapture.py などと実行した場合はどうなりますか。

**Comment by hasegaw** [comment]
関連チケット #33

**Comment by hasegaw** [comment]
```
ValueError: operands could not be broadcast together with shapes (1080,1920) (720,1280)
```
リサイズされていないんですね。720pでWiiUから出せば動く感じですかね。

**Comment by gleentea** [comment]
No module named 'ikalog'で嵌まってるので720p入力を先に試しましたが全く同じエラーでした

**Comment by hasegaw** [comment]
なるほど。とりあえずわかりました。

**Comment by gleentea** [comment]
ikalog/inputs/cvcapture.py単体では動きませんが、ikalog.pyでは動くので色々試したら、configでneed_resize=Falseにしたら類似のエラーが出たので一応ご報告を。

```
Traceback (most recent call last):
  File "IkaLog.py", line 40, in <module>
    engine.run()
  File "D:\code\IkaLog\ikalog\engine.py", line 287, in run
    self.process_frame()
  File "D:\code\IkaLog\ikalog\engine.py", line 212, in process_frame
    r = self.scn_gameresult.match(context)
  File "D:\code\IkaLog\ikalog\scenes\result_detail.py", line 319, in match
    return IkaUtils.matchWithMask(context['engine']['frame'], self.winlose_gray, 0.997, 0.20)
  File "D:\code\IkaLog\ikalog\utils\ikautils.py", line 128, in matchWithMask
    added = thresh1 + mask
ValueError: operands could not be broadcast together with shapes (1080,1920) (720,1280)
```

**Comment by hasegaw** [comment]
だいたい原因つかみました。

**Comment by gleentea** [comment]
ikalog/inputs/cvcapture.py動いたのでログ貼っておきます
WiiUの出力は720pですが、1920x1080サイズのウィンドウが出るものの黒画面でキャプチャできてませんでした。

```
***** VIDEOINPUT LIBRARY - 0.2000 - TFW2013 *****

0: b'Othello Capture 0'
1: b'AmaRec Desktop Capture'
2: b'AmaRec Video Capture'
3: b'Virtual Cam'
Please input number (or name) of capture device: 0
<__main__.CVCapture object at 0x008D16D0>: initalizing capture device 0
```

**Comment by hasegaw** [comment]
そもそもこれって起動してすぐに落ちます？それとも戦績画面で落ちます？

**Comment by hasegaw** [comment]
#33 とは関係なく、 MonsterX U3.0R で動きはじめるの戦績画面のループでうっかり生フレームデータを直接処理してしまうバグでも埋め込んだのか思ったけどもそんなことなかった？　 cvcapture.py で画面が真っ黒ということはそもそもキャプチャできていないと思うのでやはり #33 かな。状況がよくわからず。

**Comment by gleentea** [comment]
イカの状況にかかわらず、任意のタイミングでOptions->InputタブのRealtime Capture from HDMI grabberを選択肢後Applyすると落ちます（正確にはengineスレッドのみが死んでUIは活きてます）
Apply後の設定ファイルをそのまま使う場合、起動後にengineスレッドが死にます

設定ファイル的には以下の状態です（キャプチャのとこだけ抜粋）。
```
cvcapture: {Deinterlace: false, File: '', Source: camera, SourceDevice: Othello Capture
    0}
```
Sourceがamarecだと動作、cameraだと死亡です

**Comment by gleentea** [comment]
リサイズ云々で変更したWiiU側出力を1080pに戻したらcvcapture.py直実行でもキャプチャが動作しました。
そして、IkaLogUIでも動きました･･･
ちょっと動きが怪しいのであたらめて検証し治します

**Comment by hasegaw** [comment]
了解です。
cvcapture がキャプチャデバイスとの相性があることは把握しており、 OpenCV の VideoCapture 経由している限り打つ手はないので、そのせいであれば本チケットはクローズして #33 を残します。

**Comment by hasegaw** [comment]
```
  497  ffmpeg -i ~/work/splatoon/hoko_win.mp4 -s 1080x1920 1080p.mp4
  498  python3 IkaLog.py 1080p.mp4
```
で完走したので need_resize = True な限り cvcapture からとれるデータは常に 720p になっているはず。 MonsterX U3.0R は私の中では cvcapture では動かせないと思っているので今晩の調査はこれにて打ち切り。

**Comment by gleentea** [comment]
結論から言えばikalogの問題ではありませんでした。
色々試した結果、WiiU側で1080p->720p->1080pと設定を変えるとIkalogで正常にキャプチャできるので、HWもしくはドライバ側の問題のようです。
お手数かけました。

**Comment by hasegaw** [comment]
cvcapture で動いていること自体がびっくりです。デバイス名がうちと違いますしドライバが違うんでしょうかね。とりあえずクローズします。

**Comment by gleentea** [comment]
捕捉として、環境情報を残しておきます。
OS:Win7 64bit
MonsterXドライバー:1.3.13196.0（PS3キャプ可能な初期版です）
デバイス名:Othello Capture 0
cvcapture.pyを動作させるために下記パッチを当てています
https://github.com/gleentea/IkaLog/commit/3386148277528d49b0c4955d5463665ad371cefd

**Comment by hasegaw** [comment]
情報ありがとうございます。環境変数 PYTHONPATH に . もしくは ikalog/ があるディレクトリ（つまりレポジトリのルート）を指定しておくとソースコード上でモジュール検索を追加しなくても大丈夫です。ご参考まで。
