### ISSUE TITLE
sourceがビデオファイルのとき、stat.inkへの出力が行われない試合がある

### ISSUE THREAD

**Issue by thagikura** [hasegaw/IkaLog#78]
IkaConfig.py中で、
`source.start_video_file('<video_file_name>')`のようにソースをビデオファイルにしたときに、stat.inkへの書き込みが行われない試合がたまにあります(体感だと7,8試合に1試合くらい？)

失敗している試合はstatink.pyの`on_game_session_end`が呼ばれていないようです

**Comment by hasegaw** [comment]
ビデオファイル解析はどちらかというと開発テスト用機能としての位置づけで考えているので優先度低めですが不具合は不具合なのでこのIssueは開きっぱなしにしておきます

**Comment by thagikura** [comment]
了解です。ありがとうございます。stat.inkの名前間違えていたのでタイトル修正しました。

**Comment by hasegaw** [comment]
リアルタイムキャプチャの場合でも問題がおきることがあるようなので対策が必要
https://stat.ink/u/fetus_hina/104986#timeline
