### ISSUE TITLE
スクイックリンβ/バケットスロッシャーデコが別の武器として認識される

### ISSUE THREAD

**Issue by deathmetalland** [hasegaw/IkaLog#83]
@hasegaw さんの環境では問題ないでしょうか？

### スクイックリンβ

22件中8件別の武器として認識される。
* スプラチャージャーワカメ 7件
* ジェットスイーパーカスタム 1件

https://stat.ink/u/deathmetalland?filter%5Blobby%5D=&filter%5Brule%5D=&filter%5Bmap%5D=&filter%5Bweapon%5D=&filter%5Bresult%5D=&filter%5Bterm%5D=term&filter%5Bterm_from%5D=2015-12-04+00%3A00%3A00&filter%5Bterm_to%5D=2015-12-04+02%3A40%3A00

### バケットスロッシャーデコ

5件中5件バケットスロッシャーと認識される。

https://stat.ink/u/deathmetalland?filter%5Blobby%5D=&filter%5Brule%5D=&filter%5Bmap%5D=&filter%5Bweapon%5D=&filter%5Bresult%5D=&filter%5Bterm%5D=term&filter%5Bterm_from%5D=2015-12-04+02%3A41%3A00&filter%5Bterm_to%5D=2015-12-04+03%3A08%3A00

**Comment by hasegaw** [comment]
確認します。そちらのキャプチャ環境構成おしえてください。
WiiU出力解像度、しようでばいす、アマレコライブ利用時はその設定など

**Comment by deathmetalland** [comment]
@hasegaw さん、失礼しました。
キャプチャ環境は下記になります。

WiiU出力解像度: 720p
OS: Mac OS X 10.9.5
CaptureDevice: BlackmagicDesign UltraStudio Mini Recorder
HDMI Splitter: Princeton PHM-SP102A

ご確認よろしくお願いします。

**Comment by hasegaw** [comment]
なるほど、ありがとうございます。

**Comment by hasegaw** [comment]
118866-result.png
118900-result.png
118989-result.png
119030-result.png
119066-result.png
119077-result.png
119095-result.png
119213-result.png
119225-result.png
119233-result.png
119244-result.png
119250-result.png

**Comment by hasegaw** [comment]
6b7d43e で多分直ります。
UltraStudio Mini Recorder はリファレンスデバイスのつもりですのでまた誤認識などありましたら教えてください。

**Comment by deathmetalland** [comment]
誤認識しなくなりました！
